#!/bin/bash

set -x


aocl help > /dev/null 2> /dev/null || source ~/fpga/init_env.sh
rm -rf bin/*
./scripts/compile_kernel_arria10 align || exit 1
# ./scripts/compile_kernel_arria10 core  || exit 1
# ./scripts/compile_kernel_arria10 post || exit 1
# make || exit 1
# bin/host

